In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
## Sentences 
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define vocabulary size
voc_size=10000

In [8]:
## One Hot Representation 
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[4525, 1254, 8685, 3159],
 [4525, 1254, 8685, 8641],
 [4525, 8864, 8685, 7258],
 [8534, 8711, 4812, 6579, 2979],
 [8534, 8711, 4812, 6579, 502],
 [6887, 4525, 5683, 8685, 3095],
 [3638, 8906, 6720, 6579]]

In [10]:
## Word Embedding Representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4525 1254 8685 3159]
 [   0    0    0    0 4525 1254 8685 8641]
 [   0    0    0    0 4525 8864 8685 7258]
 [   0    0    0 8534 8711 4812 6579 2979]
 [   0    0    0 8534 8711 4812 6579  502]
 [   0    0    0 6887 4525 5683 8685 3095]
 [   0    0    0    0 3638 8906 6720 6579]]


In [13]:
## feature Representation 
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sasmi\Documents\ProjectLangchain\ATSLLM\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step


array([[[ 2.97729038e-02, -4.11938913e-02, -4.83682044e-02,
         -2.49869712e-02,  2.77777947e-02, -4.33225520e-02,
          1.41654350e-02,  3.07156779e-02,  3.96410935e-02,
          2.60687582e-02],
        [ 2.97729038e-02, -4.11938913e-02, -4.83682044e-02,
         -2.49869712e-02,  2.77777947e-02, -4.33225520e-02,
          1.41654350e-02,  3.07156779e-02,  3.96410935e-02,
          2.60687582e-02],
        [ 2.97729038e-02, -4.11938913e-02, -4.83682044e-02,
         -2.49869712e-02,  2.77777947e-02, -4.33225520e-02,
          1.41654350e-02,  3.07156779e-02,  3.96410935e-02,
          2.60687582e-02],
        [ 2.97729038e-02, -4.11938913e-02, -4.83682044e-02,
         -2.49869712e-02,  2.77777947e-02, -4.33225520e-02,
          1.41654350e-02,  3.07156779e-02,  3.96410935e-02,
          2.60687582e-02],
        [ 4.20977585e-02, -2.64613517e-02, -2.28447840e-03,
         -8.61593336e-03,  2.64823548e-02, -3.90223861e-02,
          1.30981468e-02, -1.07186660e-02, -1.212673

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 4525, 1254, 8685, 3159])

In [25]:
# If you want to predict the first padded doc
import numpy as np

# Correct: add batch dimension
prediction = model.predict(np.expand_dims(embedded_docs[0], axis=0))
print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[[ 0.0297729  -0.04119389 -0.0483682  -0.02498697  0.02777779
   -0.04332255  0.01416543  0.03071568  0.03964109  0.02606876]
  [ 0.0297729  -0.04119389 -0.0483682  -0.02498697  0.02777779
   -0.04332255  0.01416543  0.03071568  0.03964109  0.02606876]
  [ 0.0297729  -0.04119389 -0.0483682  -0.02498697  0.02777779
   -0.04332255  0.01416543  0.03071568  0.03964109  0.02606876]
  [ 0.0297729  -0.04119389 -0.0483682  -0.02498697  0.02777779
   -0.04332255  0.01416543  0.03071568  0.03964109  0.02606876]
  [ 0.04209776 -0.02646135 -0.00228448 -0.00861593  0.02648235
   -0.03902239  0.01309815 -0.01071867 -0.01212673  0.04218768]
  [-0.03309681  0.04439694 -0.04268518  0.04252081 -0.00950608
   -0.04893013 -0.04303931 -0.03555164  0.00934967  0.01850846]
  [ 0.01321637  0.00176037 -0.03642795  0.00473486  0.00485893
   -0.00455851 -0.01885334 -0.03798896  0.04616782 -0.00327765]
  [-0.01383543 -0.01150061 -0.02816457 -0.01427526 -0.02484624
   -0.0342